FROM node:20-bullseye-slim
WORKDIR /frontend
ARG REACT_APP_BASE_URL
ENV REACT_APP_BASE_URL ${REACT_APP_BASE_URL}
COPY ./frontend/package.json /frontend/package.json
COPY ./frontend/package-lock.json /frontend/package-lock.json
RUN npm i
RUN npm i -g serve
COPY ./frontend ./
RUN npm run production