version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - .env
    command: "npm run production"
    restart: "always"
    ports:
      - "5000:5000"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_BASE_URL=$REACT_APP_BASE_URL
    env_file:
      - .env
    command: "serve -s build -l 3000"
    restart: "always"
    ports:
      - "3000:3000"
